export const products = [
  {
    name: 'Rolex Submariner Watch',
    brand: 'Rolex',
    model: 'Підводний мисливець',
    price: 15000,
    case_material: 'Нержавіюча сталь',
    strap_material: 'Гума',
    dial_color: 'Чорний',
    water_resistance: '300 метрів',
    functions: ['Дата', 'Поворотний безель', 'Автоматичний завод'],
    features: [
      'Люмінесцентні маркери',
      'Подвійна прокручувана корона',
      'Прозора задня кришка',
    ],
  },
  {
    name: 'TAG Heuer Carrera Chronograph',
    brand: 'TAG Heuer',
    model: 'Хронограф Carrera',
    price: 8500,
    case_material: 'Нержавіюча сталь',
    strap_material: 'Шкіра',
    dial_color: 'Синій',
    water_resistance: '100 метрів',
    functions: ['Хронограф', 'Дата', 'Тахіметр'],
    features: [
      'Сапфіровий кристал',
      'Прозора задня кришка',
      'Люмінесцентні стрілки',
    ],
  },
  {
    name: "Seiko Prospex Diver's",
    brand: 'Seiko',
    model: 'Prospex Diver',
    price: 450,
    case_material: 'Нержавіюча сталь',
    strap_material: 'Силікон',
    dial_color: 'Чорний',
    water_resistance: '200 метрів',
    functions: ['Дата', 'Поворотний безель', 'Люмінесцентні маркери'],
    features: ['Кристал Hardlex', 'Гвинтова корона'],
  },
  {
    name: 'Citizen Eco-Drive Dress',
    brand: 'Citizen',
    model: 'Eco-Drive Dress',
    price: 250,
    case_material: 'Нержавіюча сталь',
    strap_material: 'Шкіра',
    dial_color: 'Сріблястий',
    water_resistance: '30 метрів',
    functions: ['Дата', 'Сонячний панельний', 'Римські цифри'],
    features: ['Мінеральний кристал', 'Плавний регулятор'],
  },
  {
    name: 'Fossil Minimalist Analog',
    brand: 'Fossil',
    model: 'Minimalist',
    price: 100,
    case_material: 'Нержавіюча сталь',
    strap_material: 'Металева сітка',
    dial_color: 'Білий',
    water_resistance: '50 метрів',
    functions: ['Аналоговий', 'Дата'],
    features: ['Мінеральний кристал', 'Висувна корона'],
  },
  {
    name: 'Omega Speedmaster',
    brand: 'Omega',
    model: 'Speedmaster Moonwatch',
    price: 5000,
    case_material: 'Нержавіюча сталь',
    strap_material: 'Нейлонова тканина',
    dial_color: 'Чорний',
    water_resistance: '50 метрів',
    functions: ['Хронограф', 'Тахіметр', 'Ручне заводження'],
    features: ['Гесалітовий кристал', 'Гвинтова корона'],
  },
  {
    name: 'Bulova Precisionist Chronograph',
    brand: 'Bulova',
    model: 'Precisionist',
    price: 300,
    case_material: 'Нержавіюча сталь',
    strap_material: 'Шкіра',
    dial_color: 'Сріблястий',
    water_resistance: '100 метрів',
    functions: ['Хронограф', 'Дата', 'Тахіметр'],
    features: ['Мінеральний кристал', 'Гвинтова корона'],
  },
  {
    name: 'Casio G-Shock Digital',
    brand: 'Casio',
    model: 'G-Shock',
    price: 120,
    case_material: 'Смола',
    strap_material: 'Смола',
    dial_color: 'Чорний',
    water_resistance: '200 метрів',
    functions: ['Цифровий', 'Відштовхування від ударів', 'Світовий час'],
    features: ['Мінеральний кристал', 'Кнопкова корона'],
  },
  {
    name: 'Tissot Le Locle Automatic',
    brand: 'Tissot',
    model: 'Le Locle',
    price: 700,
    case_material: 'Нержавіюча сталь',
    strap_material: 'Шкіра',
    dial_color: 'Білий',
    water_resistance: '30 метрів',
    functions: ['Дата', 'Автоматичний', 'Римські цифри'],
    features: ['Сапфіровий кристал', 'Висувна корона'],
  },
  {
    name: 'Longines Master Collection',
    brand: 'Longines',
    model: 'Master Collection',
    price: 1800,
    case_material: 'Нержавіюча сталь',
    strap_material: 'Шкіра',
    dial_color: 'Синій',
    water_resistance: '30 метрів',
    functions: ['Дата', 'Автоматичний', 'Фаза місяця'],
    features: ['Сапфіровий кристал', 'Гвинтова корона'],
  },
  {
    name: 'Hamilton Khaki Field Mechanical',
    brand: 'Hamilton',
    model: 'Khaki Field Mechanical',
    price: 400,
    case_material: 'Нержавіюча сталь',
    strap_material: 'Тканина',
    dial_color: 'Чорний',
    water_resistance: '50 метрів',
    functions: ['Аналоговий', 'Дата', 'Ручне заводження'],
    features: ['Сапфіровий кристал', 'Висувна корона'],
  },
  {
    name: 'Movado Museum Classic',
    brand: 'Movado',
    model: 'Museum Classic',
    price: 600,
    case_material: 'Нержавіюча сталь',
    strap_material: 'Шкіра',
    dial_color: 'Чорний',
    water_resistance: '30 метрів',
    functions: ['Аналоговий', 'Швейцарський кварц', 'Точковий маркер'],
    features: ['Сапфіровий кристал', 'Висувна корона'],
  },
  {
    name: 'Citizen Promaster Dive',
    brand: 'Citizen',
    model: 'Promaster Dive',
    price: 300,
    case_material: 'Нержавіюча сталь',
    strap_material: 'Гума',
    dial_color: 'Чорний',
    water_resistance: '200 метрів',
    functions: ['Дата', 'Поворотний безель', 'Eco-Drive'],
    features: ['Мінеральний кристал', 'Гвинтова корона'],
  },
  {
    name: 'Rado True Thinline',
    brand: 'Rado',
    model: 'True Thinline',
    price: 1200,
    case_material: 'Кераміка',
    strap_material: 'Кераміка',
    dial_color: 'Білий',
    water_resistance: '30 метрів',
    functions: ['Аналоговий', 'Швейцарський кварц', 'Мінімалістичний дизайн'],
    features: ['Сапфіровий кристал', 'Тискуюча-тягуча корона'],
  },
  {
    name: 'Oris Aquis Date',
    brand: 'Oris',
    model: 'Aquis Date',
    price: 900,
    case_material: 'Нержавіюча сталь',
    strap_material: 'Гума',
    dial_color: 'Синій',
    water_resistance: '300 метрів',
    functions: ['Дата', 'Поворотний безель', 'Автоматичний'],
    features: ['Сапфіровий кристал', 'Гвинтова корона'],
  },
  {
    name: 'Breitling Avenger Chronograph',
    brand: 'Breitling',
    model: 'Avenger Chronograph',
    price: 5500,
    case_material: 'Нержавіюча сталь',
    strap_material: 'Гума',
    dial_color: 'Чорний',
    water_resistance: '300 метрів',
    functions: ['Хронограф', 'Дата', 'Автоматичний'],
    features: ['Сапфіровий кристал', 'Гвинтова корона'],
  },
  {
    name: 'Panerai Luminor Marina',
    brand: 'Panerai',
    model: 'Luminor Marina',
    price: 8500,
    case_material: 'Нержавіюча сталь',
    strap_material: 'Шкіра',
    dial_color: 'Чорний',
    water_resistance: '300 метрів',
    functions: ['Дата', 'Піддиск секунд', 'Ручне заводження'],
    features: ['Сапфіровий кристал', 'Гвинтова корона'],
  },
  {
    name: 'Mido Baroncelli Heritage',
    brand: 'Mido',
    model: 'Baroncelli Heritage',
    price: 550,
    case_material: 'Нержавіюча сталь',
    strap_material: 'Шкіра',
    dial_color: 'Білий',
    water_resistance: '30 метрів',
    functions: ['Дата', 'Автоматичний', 'Римські цифри'],
    features: ['Сапфіровий кристал', 'Висувна корона'],
  },
  {
    name: 'Gucci G-Timeless',
    brand: 'Gucci',
    model: 'G-Timeless',
    price: 1200,
    case_material: 'Нержавіюча сталь',
    strap_material: 'Шкіра',
    dial_color: 'Чорний',
    water_resistance: '50 метрів',
    functions: ['Аналоговий', 'Дата', 'Мотив бджілки'],
    features: ['Сапфіровий кристал', 'Висувна корона'],
  },
  {
    name: 'Zenith El Primero Chronograph',
    brand: 'Zenith',
    model: 'El Primero Chronograph',
    price: 6800,
    case_material: 'Нержавіюча сталь',
    strap_material: 'Шкіра',
    dial_color: 'Сріблястий',
    water_resistance: '100 метрів',
    functions: ['Хронограф', 'Дата', 'Автоматичний'],
    features: ['Сапфіровий кристал', 'Тискуюча-тягуча корона'],
  },
];